const $ = (id) => document.getElementById(id);
async function load() {
  const config = await window.mirocab.getConfig(); $("enabled").checked = config.enabled; $("token").value = config.pairingToken;
  $("enabled").onchange = () => window.mirocab.saveConfig({ enabled: $("enabled").checked });
  $("copyToken").onclick = () => navigator.clipboard.writeText($("token").value);
  const printers = await window.mirocab.printers(); const printerSelect = $("profilePrinter"); const queueSelect = $("queuePrinter"); printers.forEach((p) => { printerSelect.add(new Option(p.name, p.name)); queueSelect.add(new Option(p.name, p.name)); });
  $("printerList").replaceChildren(...printers.map((printer) => { const row = document.createElement("div"); row.className = "printer"; row.innerHTML = `<div><b>${printer.name}</b><small>${printer.isDefault ? "پیش‌فرض ویندوز" : ""}</small></div><button>تست چاپ</button>`; row.querySelector("button").onclick = async () => { row.querySelector("button").disabled = true; try { await window.mirocab.testPrint(printer.name); alert("job تست به Windows Spooler ارسال شد."); } catch (e) { alert(e.message); } finally { row.querySelector("button").disabled = false; } }; return row; }));
  const refreshJobs = async () => { const host = $("jobList"); host.textContent = "در حال دریافت صف…"; try { const jobs = await window.mirocab.jobs(queueSelect.value); host.replaceChildren(...(jobs.length ? jobs.map((job) => { const row = document.createElement("div"); row.className = "printer"; const title = document.createElement("div"); title.innerHTML = `<b>${job.document || "بدون نام"}</b><small>Job #${job.id} · ${job.pagesPrinted}/${job.totalPages || "?"}</small>`; row.append(title); [ ["توقف", "pause"], ["ادامه", "resume"], ["لغو", "cancel"] ].forEach(([label, action]) => { const button = document.createElement("button"); button.textContent = label; button.onclick = async () => { button.disabled = true; try { await window.mirocab.controlJob(queueSelect.value, job.id, action); await refreshJobs(); } catch (e) { alert(e.message); button.disabled = false; } }; row.append(button); }); return row; }) : [Object.assign(document.createElement("p"), { textContent: "Job فعالی در صف نیست." })])); } catch (e) { host.textContent = `خطا در دریافت صف: ${e.message}`; } };
  $("refreshJobs").onclick = refreshJobs; queueSelect.onchange = refreshJobs; await refreshJobs();
  const fixed = { statement_a5: "صورت‌وضعیت همیشه A5 و Portrait است.", cargo_a5: "بارنامه A5 همیشه Landscape است.", cargo_thermal: "دو job مستقل و Cut بعد از هر نسخه اجباری است." };
  const updateRollControls = () => { const paper = $("profilePaper").value; const isRoll = paper !== "A5"; $("rollSettings").hidden = !isRoll; $("customRollWidthField").hidden = paper !== "custom-roll"; $("rollWidthMm").disabled = paper !== "custom-roll"; $("rollHeightMm").disabled = !isRoll; $("profileCutMode").disabled = !isRoll; if (paper === "thermal-58") $("rollWidthMm").value = 58; if (paper === "thermal-80") $("rollWidthMm").value = 80; };
  const syncProfile = () => { const item = config.profileSettings[$("profile").value] || {}; const isFixed = ["statement_a5", "cargo_a5"].includes($("profile").value); $("profilePrinter").value = item.printer || printers.find((p) => p.isDefault)?.name || ""; $("profilePaper").value = item.paper || (isFixed ? "A5" : "thermal-80"); $("profileOrientation").value = item.orientation || (isFixed ? ($("profile").value === "cargo_a5" ? "landscape" : "portrait") : "portrait"); $("profileCopies").value = item.copies || 1; $("profileScale").value = item.scale || 100; ["marginTop", "marginRight", "marginBottom", "marginLeft"].forEach((id) => { $(id).value = item[id] || 0; }); $("rollWidthMm").value = item.rollHeightMm || 130; $("profileCutMode").value = item.cutMode || "none"; $("profilePaper").disabled = isFixed; $("profileOrientation").disabled = isFixed; updateRollControls(); $("profileRule").textContent = fixed[$("profile").value] || "پرینتر، کاغذ، جهت، Scale، حاشیه و طول خودکار سند برای این نوع سند ذخیره می‌شود."; };
  $("profile").onchange = syncProfile; $("profilePaper").onchange = updateRollControls; syncProfile();
  $("saveProfile").onclick = async () => { const key = $("profile").value; const setting = { printer: $("profilePrinter").value, paper: $("profilePaper").value, orientation: $("profileOrientation").value, copies: Number($("profileCopies").value), scale: Number($("profileScale").value), marginTop: Number($("marginTop").value), marginRight: Number($("marginRight").value), marginBottom: Number($("marginBottom").value), marginLeft: Number($("marginLeft").value), rollWidthMm: Number($("rollWidthMm").value), rollHeightMm: Number($("rollHeightMm").value), cutMode: $("profileCutMode").value }; const next = { ...config.profileSettings, [key]: setting }; await window.mirocab.saveConfig({ profileSettings: next }); config.profileSettings = next; alert("تنظیمات این سیستم ذخیره شد."); };
} load();
