const $ = (id) => document.getElementById(id);
async function load() {
  const config = await window.mirocab.getConfig(); $("enabled").checked = config.enabled; $("token").value = config.pairingToken;
  $("enabled").onchange = () => window.mirocab.saveConfig({ enabled: $("enabled").checked });
  $("copyToken").onclick = () => navigator.clipboard.writeText($("token").value);
  $("saveOrigin").onclick = async () => { const origin = $("origin").value.trim(); if (!/^https?:\/\//.test(origin)) return alert("آدرس پنل معتبر نیست."); const allowedOrigins = [...new Set([...config.allowedOrigins, origin])]; await window.mirocab.saveConfig({ allowedOrigins }); $("origin").value = ""; alert("آدرس مجاز ذخیره شد."); };
  const printers = await window.mirocab.printers(); const printerSelect = $("profilePrinter"); const queueSelect = $("queuePrinter"); printers.forEach((p) => { printerSelect.add(new Option(p.name, p.name)); queueSelect.add(new Option(p.name, p.name)); });
  $("printerList").replaceChildren(...printers.map((printer) => { const row = document.createElement("div"); row.className = "printer"; row.innerHTML = `<div><b>${printer.name}</b><small>${printer.isDefault ? "پیش‌فرض ویندوز" : ""}</small></div><button>تست چاپ</button>`; row.querySelector("button").onclick = async () => { row.querySelector("button").disabled = true; try { await window.mirocab.testPrint(printer.name); alert("job تست به Windows Spooler ارسال شد."); } catch (e) { alert(e.message); } finally { row.querySelector("button").disabled = false; } }; return row; }));
  const refreshJobs = async () => { const host = $("jobList"); host.textContent = "در حال دریافت صف…"; try { const jobs = await window.mirocab.jobs(queueSelect.value); host.replaceChildren(...(jobs.length ? jobs.map((job) => { const row = document.createElement("div"); row.className = "printer"; const title = document.createElement("div"); title.innerHTML = `<b>${job.document || "بدون نام"}</b><small>Job #${job.id} · ${job.pagesPrinted}/${job.totalPages || "?"}</small>`; row.append(title); [ ["توقف", "pause"], ["ادامه", "resume"], ["لغو", "cancel"] ].forEach(([label, action]) => { const button = document.createElement("button"); button.textContent = label; button.onclick = async () => { button.disabled = true; try { await window.mirocab.controlJob(queueSelect.value, job.id, action); await refreshJobs(); } catch (e) { alert(e.message); button.disabled = false; } }; row.append(button); }); return row; }) : [Object.assign(document.createElement("p"), { textContent: "Job فعالی در صف نیست." })])); } catch (e) { host.textContent = `خطا در دریافت صف: ${e.message}`; } };
  $("refreshJobs").onclick = refreshJobs; queueSelect.onchange = refreshJobs; await refreshJobs();
  const fixed = { statement_a5: "صورت‌وضعیت همیشه A5 و Portrait است.", cargo_a5: "بارنامه A5 همیشه Landscape است.", cargo_thermal: "دو job مستقل و Cut بعد از هر نسخه اجباری است." };
  const syncProfile = () => { const item = config.profileSettings[$("profile").value] || {}; $("profilePrinter").value = item.printer || printers.find((p) => p.isDefault)?.name || ""; $("profilePaper").value = item.paper || ($("profile").value === "statement_a5" || $("profile").value === "cargo_a5" ? "A5" : "thermal-80"); $("profileCopies").value = item.copies || 1; const isFixed = ["statement_a5", "cargo_a5"].includes($("profile").value); $("profilePaper").disabled = isFixed; $("profileRule").textContent = fixed[$("profile").value] || "بلیت و گزارش راننده می‌توانند A5 یا حرارتی باشند."; };
  $("profile").onchange = syncProfile; syncProfile();
  $("saveProfile").onclick = async () => { const key = $("profile").value; const next = { ...config.profileSettings, [key]: { printer: $("profilePrinter").value, paper: $("profilePaper").value, copies: Number($("profileCopies").value) } }; await window.mirocab.saveConfig({ profileSettings: next }); config.profileSettings = next; alert("تنظیمات این سیستم ذخیره شد."); };
} load();
