const $ = (id) => document.getElementById(id);
async function load() {
  const config = await window.mirocab.getConfig(); $("enabled").checked = config.enabled; $("token").value = config.pairingToken;
  $("enabled").onchange = () => window.mirocab.saveConfig({ enabled: $("enabled").checked });
  $("copyToken").onclick = () => navigator.clipboard.writeText($("token").value);
  const printers = await window.mirocab.printers();
  let selectedPrinter = "";
  const fixed = { statement_a5: "صورت‌وضعیت همیشه A5 و Portrait است.", cargo_a5: "بارنامه A5 همیشه Landscape است.", cargo_thermal: "چاپ دوم پس از خالی‌شدن صف ویندوز ارسال می‌شود." };
  const updateRollControls = () => { const paper = $("profilePaper").value; const isRoll = paper !== "A5"; $("rollSettings").hidden = !isRoll; $("customRollWidthField").hidden = paper !== "custom-roll"; $("rollWidthMm").disabled = paper !== "custom-roll"; $("rollHeightMm").disabled = !isRoll; $("profileCutMode").disabled = !isRoll; if (paper === "thermal-58") $("rollWidthMm").value = 58; if (paper === "thermal-80") $("rollWidthMm").value = 80; };
  const renderSelectedPrinter = () => { $("selectedPrinter").textContent = selectedPrinter || "انتخاب پرینتر"; $("choosePrinter").classList.toggle("is-empty", !selectedPrinter); };
  const syncProfile = () => { const item = config.profileSettings[$("profile").value] || {}; const isFixed = ["statement_a5", "cargo_a5"].includes($("profile").value); selectedPrinter = item.printer || ""; renderSelectedPrinter(); $("profilePaper").value = item.paper || (isFixed ? "A5" : "thermal-80"); $("profileOrientation").value = item.orientation || (isFixed ? ($("profile").value === "cargo_a5" ? "landscape" : "portrait") : "portrait"); $("profileCopies").value = item.copies || 1; $("profileScale").value = item.scale || 100; ["marginTop", "marginRight", "marginBottom", "marginLeft"].forEach((id) => { $(id).value = item[id] || 0; }); $("rollWidthMm").value = item.rollWidthMm || ($("profilePaper").value === "thermal-58" ? 58 : 80); $("rollHeightMm").value = item.rollHeightMm || 130; $("profileCutMode").value = item.cutMode || "none"; $("profilePaper").disabled = isFixed; $("profileOrientation").disabled = isFixed; updateRollControls(); $("profileRule").textContent = fixed[$("profile").value] || "پرینتر، کاغذ، جهت، Scale، حاشیه و طول رول برای این نوع سند ذخیره می‌شود."; };
  const closePrinterModal = () => { $("printerModal").hidden = true; $("choosePrinter").focus(); };
  const openPrinterModal = () => { const profileName = $("profile").selectedOptions[0].textContent; $("printerModalDescription").textContent = `پرینتر مورد استفاده برای «${profileName}» را انتخاب کنید.`; const list = $("modalPrinterList"); list.replaceChildren(...printers.map((printer) => { const button = document.createElement("button"); button.type = "button"; button.className = "modal-printer"; button.classList.toggle("selected", printer.name === selectedPrinter); const name = document.createElement("b"); name.textContent = printer.name; button.append(name); if (printer.name === selectedPrinter) { const marker = document.createElement("span"); marker.textContent = "انتخاب‌شده"; button.append(marker); } button.onclick = () => { selectedPrinter = printer.name; renderSelectedPrinter(); closePrinterModal(); }; return button; })); $("noPrinters").hidden = printers.length > 0; $("printerModal").hidden = false; (list.querySelector("button") || $("closePrinterModal")).focus(); };
  $("choosePrinter").onclick = openPrinterModal; $("closePrinterModal").onclick = closePrinterModal; document.querySelector("[data-close-printer-modal]").onclick = closePrinterModal;
  document.addEventListener("keydown", (event) => { if (event.key === "Escape" && !$("printerModal").hidden) closePrinterModal(); });
  $("profile").onchange = syncProfile; $("profilePaper").onchange = updateRollControls; syncProfile();
  $("saveProfile").onclick = async () => { const key = $("profile").value; if (!selectedPrinter) return alert("ابتدا پرینتر این نوع سند را انتخاب کنید."); const setting = { printer: selectedPrinter, paper: $("profilePaper").value, orientation: $("profileOrientation").value, copies: Number($("profileCopies").value), scale: Number($("profileScale").value), marginTop: Number($("marginTop").value), marginRight: Number($("marginRight").value), marginBottom: Number($("marginBottom").value), marginLeft: Number($("marginLeft").value), rollWidthMm: Number($("rollWidthMm").value), rollHeightMm: Number($("rollHeightMm").value), cutMode: $("profileCutMode").value }; const next = { ...config.profileSettings, [key]: setting }; await window.mirocab.saveConfig({ profileSettings: next }); config.profileSettings = next; alert("تنظیمات این سیستم ذخیره شد."); };
  $("testProfile").onclick = async () => { const button = $("testProfile"); button.disabled = true; try { await window.mirocab.testPrint($("profile").value); alert("job تست با پروفایل ذخیره‌شدهٔ میروکب ارسال شد."); } catch (e) { alert(e.message); } finally { button.disabled = false; } };
} load();
